### PR TITLE
Prevent null selectedDraft from breaking render

### LINKED ISSUE #218: Bug: Invalidating YAML Breaks Longform Panel
**Versions**
Longform version: 2.0.4
Obsidian version: 1.4.16
OS [e.g. macOS, Windows, iOS, Android]: Windows

**Describe the bug**
Invalidating the YAML breaks the longform panel.  If the YAML is repaired, scenes can still be selected, and projects can be switched, but you cannot open another tab until you refresh Obsidian.

**To Reproduce**
1. Open a valid index file
2. Open the longform explorer view
3. In source mode, add a tab character before the opening `---`
4. Wait about a second

**Expected behavior**
The Longform panel is still responsive

**Screenshots**

**Additional context**
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'vaultPath')
    at eval (plugin:longform:30821:79)
    at Array.findIndex (<anonymous>)
    at $$self.$$.update (plugin:longform:30821:33)
    at update (plugin:longform:2848:12)
    at flush (plugin:longform:2819:13)
 ```

### PR DESCRIPTION
**Pull request by b-camphart**
fixes #218

### CODE REVIEW

File: src/view/compile/CompileView.svelte [hunk 1]
```diff
@@ -63,9 +63,9 @@
         allWorkflowNames.length > 0
       ) {
         // shadowed here to prevent circular reference
-        const _currentDraftIndex = $drafts.findIndex(
-          (d) => d.vaultPath === $selectedDraft.vaultPath
-        );
+        const _currentDraftIndex =
+          $selectedDraft &&
```
Comment (kevboh) [inline src/view/compile/CompileView.svelte:67]: Is this not already checked twice above? Is this needed?

File: src/view/explorer/SceneList.svelte [hunk 2]
```diff
@@ -230,9 +230,9 @@
   }
 
   function doWithUnknown(fileName: string, action: "add" | "ignore") {
-    const currentDraftIndex = $drafts.findIndex(
-      (d) => d.vaultPath === $selectedDraft.vaultPath
-    );
+    const currentDraftIndex =
+      $selectedDraft &&
+      $drafts.findIndex((d) => d.vaultPath === $selectedDraft.vaultPath);
```
Comment (kevboh) [inline src/view/explorer/SceneList.svelte:235]: I think this would be more readable (and not make people reason about an undefined `currentDraftIndex` as

```suggestion
    if (!$selectedDraft) {
        return
    }
    const currentDraftIndex = $drafts.findIndex((d) => d.vaultPath === $selectedDraft.vaultPath);
```

File: src/view/explorer/SceneList.svelte [hunk 3]
```diff
@@ -20,9 +20,9 @@
 
   let currentDraftIndex: number;
   $: {
-    currentDraftIndex = $drafts.findIndex(
-      (d) => d.vaultPath === $selectedDraft.vaultPath
-    );
+    currentDraftIndex =
+      $selectedDraft &&
+      $drafts.findIndex((d) => d.vaultPath === $selectedDraft.vaultPath);
   }
```
Comment (kevboh) [inline src/view/explorer/SceneList.svelte:26]: What does an undefined `currentDraftIndex` mean? Is it handled throughout? I believe this whole block could also be written as

```
$: if ($selectedDraft) {
    currentDraftIndex = $drafts.findIndex(
      (d) => d.vaultPath === $selectedDraft.vaultPath
    );
}
```

File: src/view/explorer/SceneList.svelte [hunk 4]
```diff
@@ -255,9 +255,9 @@
...
 
   function doWithAll(action: "add" | "ignore") {
-    const currentDraftIndex = $drafts.findIndex(
-      (d) => d.vaultPath === $selectedDraft.vaultPath
-    );
+    const currentDraftIndex =
```
Comment (kevboh) [inline src/view/explorer/SceneList.svelte:258]: Same suggestion as above

**Review by kevboh — CHANGES_REQUESTED** [review]
See suggestions—I want to make sure undefined indices are handled and can be read cleanly. Thanks for the PR!

**Comment by b-camphart** [comment]
@kevboh applied suggestions!  Also, I found another bug related to this in which steps in a workflow were sometimes `undefined`, causing the same issue of the panel being unresponsive.  I removed a binding in a svelte component, which I didn't think was necessary, since the component never actually updated it.  Seems to have fixed that problem, and the fix doesn't seem to have changed any functionality.

File: src/view/explorer/scene-menu-items.ts [hunk 5]
```diff
@@ -5,6 +5,7 @@ import { get } from "svelte/store";
 
 const getSelectedDraftWithIndex = () => {
     const draft = get(selectedDraft) as MultipleSceneDraft;
+    if (draft == null) return { index: -1, draft };
```
Comment (kevboh) [inline src/view/explorer/scene-menu-items.ts:8]: Don't use double equals, wrap if body in curly brackets

```suggestion
    if (!draft) {
        return { index: -1, draft };
    }
```

File: src/view/explorer/scene-menu-items.ts [hunk 6]
```diff
@@ -13,6 +14,7 @@ const getSelectedDraftWithIndex = () => {
 
 export const addScene = (fileName: string) => {
     const { index, draft } = getSelectedDraftWithIndex()
+    if (draft == null) return;
```
Comment (kevboh) [inline src/view/explorer/scene-menu-items.ts:17]:
```suggestion
    if (!draft) {
        return;
    }
```

File: src/view/explorer/scene-menu-items.ts [hunk 7]
```diff
@@ -29,6 +31,7 @@ export const addScene = (fileName: string) => {
 
 export const ignoreScene = (fileName: string) => {
     const { index, draft } = getSelectedDraftWithIndex()
+    if (draft == null) return;
```
Comment (kevboh) [inline src/view/explorer/scene-menu-items.ts:34]:
```suggestion
    if (!draft) {
        return;
    }
```

File: src/view/explorer/scene-menu-items.ts [hunk 8]
```diff
@@ -46,6 +49,7 @@ export const ignoreScene = (fileName: string) => {
 
 export const addAll = () => {
     const { index, draft } = getSelectedDraftWithIndex()
+    if (draft == null) return;
```
Comment (kevboh) [inline src/view/explorer/scene-menu-items.ts:52]:
```suggestion
    if (!draft) {
        return;
    }
```

File: src/view/explorer/scene-menu-items.ts [hunk 9]
```diff
@@ -61,6 +65,7 @@ export const addAll = () => {
 
 export const ignoreAll = () => {
     const { index, draft } = getSelectedDraftWithIndex()
+    if (draft == null) return;
```
Comment (kevboh) [inline src/view/explorer/scene-menu-items.ts:68]:
```suggestion
    if (!draft) {
        return;
    }
```

**Review by kevboh — CHANGES_REQUESTED** [review]
Nearly there.

**Review by kevboh — APPROVED** [review]
