### PR TITLE
Relative Compile Paths

### LINKED ISSUE #149: Bug: Unexpected Behavior when Compile Output Path set to Parent Folder
**Versions**
Longform version: 2.0.3
Obsidian version: 1.1.16
OS: Windows
Theme: Things
Other plugins: [AidenLx's Folder Note](https://github.com/aidenlx/alx-folder-note) 

**Describe the bug**
I use a folder note plugin that will connect a .md file to a folder with the same name, if that file is saved in the same parent directory as the folder. It works really well, and I like that I can set my own output path in the "Save as Note" step in Longform's compiler so that I can have it directly update the folder note I created for my Longform folder.

Currently, I have my output path set to "../$1.md", which saves the compiled manuscript to the parent folder of the Longform project, with the name set to the project name. As I have already set up a folder note for the Longform project, my compiled manuscript automatically populates in the folder note. It's great!

The one issue I've noticed, however, is that the "../" part of the output path pointing to the parent folder seems to be blocking the Longform plugin from opening the newly compiled .md file once it's compiled. I get the following notifications when compiling is complete:

"Compile Complete"
"File names cannot end with a dot or a space"

Then, a new tab is opened in the background, and it stays on the "No file is open" screen.

This isn't a huge issue for me, but I wanted to report it because I think this is a somewhat uncommon use case that may have an easy workaround (i.e., a $0 variable set to the parent or root directory, or an option to supply an absolute path instead of a relative path). Alternatively, they may be some tweaking that can be done with how the plugin communicates with Obsidian so that it can open a wider variety of custom output paths without running into limitations with how Obsidian opens files. I'm not familiar with Obsidian's API so I can't say what the exact issue is, but I can say that the plugin is doing exactly what I'm asking it to, and it's just not displaying the completed file.

**To Reproduce**
1. In the longform tab, navigate to "Compile"
2. Under the "Save as Note" step, enter "../$1.md" to the file path
3. Click "Compile"

**Expected behavior**
A new view tab should open displaying the newly compiled markdown note.

I've tested a few different output paths and found that the issue only appears when the "../" prefix is present in the output path. "$1.md" will work as expected, with the file being saved to the project folder.

I also tried compiling the file with no folder note set to the project file and "../$1.md" set to the output path. The same issue appeared whether or not a folder note or note by the same name already existed.

This is a fantastic plugin, thank you for working on it!

### PR DESCRIPTION
**Pull request by b-camphart**
Introduces a new function for resolving relative file paths during compilation.  Checks for many possible paths that could start with a dot.  Some of which can be handled, some can't.  Also, allows valid file paths to be compiled, but gives a warning if obsidian won't be able to open them.

fix #149

### CODE REVIEW

**Comment by b-camphart** [comment]
[26fad01](https://github.com/kevboh/longform/pull/187/commits/26fad0121ea0f6320d60bef0f4898a01dfe841b0) shouldn't be included in this PR if/when #186 is merged.

**Comment by b-camphart** [comment]
Should fix #149

**Comment by b-camphart** [comment]
@kevboh 
> @b-camphart can you rebase onto `main` to remove the extraneous commit?

Done! 🙂

File: src/compile/steps/write-to-note.ts [hunk 1]
```diff
@@ -1,11 +1,74 @@
...
   makeBuiltinStep,
 } from "./abstract-compile-step";
 
+function resolvePath(
+  projectPath: string,
+  relativeFilePath: string,
+): string {
+  relativeFilePath = relativeFilePath.endsWith(".md") ? relativeFilePath : relativeFilePath + ".md";
+
+  if (! relativeFilePath.startsWith(".")) {
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:15]:
```suggestion
  if (!relativeFilePath.startsWith(".")) {
```

File: src/compile/steps/write-to-note.ts [hunk 2]
```diff
@@ -1,11 +1,74 @@
...
+    return normalizePath(`${projectPath}/${relativeFilePath}`);
+  }
+
+  /*
+  Possible paths:
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:20]: Thank you for this list!

File: src/compile/steps/write-to-note.ts [hunk 3]
```diff
@@ -1,11 +1,74 @@
...
+    ...md
+    .../filename.md
+    ./.../filename.md
+    .md -> impossible due to blank check in WriteToNoteStep
+  */
+ 
+  const filePathComponents = relativeFilePath.split('/');
+  if (filePathComponents.length === 1) {
+    // dealing with .filename.md path
+    new Notice("Obsidian cannot open files that begin with a dot.  Consider a different name.");
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:40]:
```suggestion
    new Notice("Obsidian cannot open files that begin with a dot. Consider a different name.");
```

File: src/compile/steps/write-to-note.ts [hunk 4]
```diff
@@ -1,11 +1,74 @@
...
+      throw new Error('Invalid path for Save as Note.');
+    }
+    projectPathComponents.pop();
+    if (filePathComponents[0] === '..') {
+      filePathComponent = filePathComponents.shift();
+    } else {
+      break;
+    }
+    atStartOfPath = false;
+  } while (filePathComponents.length > 1)
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:65]: This is a very difficult block of code to reason about. I would probably reach for recursion here, but if you're not comfortable doing that could you annotate each meaningful line with a comment explaining what's going on?

File: src/compile/steps/write-to-note.ts [hunk 5]
```diff
@@ -1,11 +1,74 @@
...
+
+  return normalizePath(projectPathComponents.concat(filePathComponents).join("/"));
+
+
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:69]:
```suggestion
  return normalizePath(projectPathComponents.concat(filePathComponents).join("/"));
```

Comment (kevboh) [reply src/compile/steps/write-to-note.ts:69]: (removing newlines)

File: src/compile/steps/write-to-note.ts [hunk 6]
```diff
@@ -44,22 +107,30 @@ export const WriteToNoteStep = makeBuiltinStep({
...
 
       try {
-        await context.app.vault.createFolder(pathComponents.join("/"));
+        await context.app.vault.createFolder(containingFolderPath);
       } catch (e) {
         // do nothing, folder already existed
       }
 
-      await context.app.vault.adapter.write(path, input.contents);
+      console.log('Writing to:', filePath);
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:122]: I've tried to namespace all logged text with `[Longform]`:

```suggestion
      console.log('[Longform] Writing to:', filePath);
```

File: src/compile/steps/write-to-note.ts [hunk 7]
```diff
@@ -44,22 +107,30 @@ export const WriteToNoteStep = makeBuiltinStep({
...
+
+      await context.app.vault.adapter.write(filePath, input.contents);
 
       if (openAfter) {
-        context.app.workspace.openLinkText(path, "/", true);
+        console.log('Attempting to open:', filePath);
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:127]:
```suggestion
        console.log('[Longform] Attempting to open:', filePath);
```

File: src/compile/steps/write-to-note.ts [hunk 8]
```diff
@@ -44,22 +107,30 @@ export const WriteToNoteStep = makeBuiltinStep({
...
+
+        context.app.workspace.openLinkText(filePath, "/", true)
+          .catch(err => {
+            console.error('Could not open', filePath);
+            console.error(err);
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:132]:
```suggestion
            console.error('[Longform] Could not open', filePath, err);
```

**Review by kevboh — CHANGES_REQUESTED** [review]

File: src/compile/steps/write-to-note.ts (hunk 6 above)
Comment (b-camphart) [reply src/compile/steps/write-to-note.ts:122]: Good to know!  I'll keep that in mind for future logging stuff 🙂

File: src/compile/steps/write-to-note.ts (hunk 5 above)
Comment (b-camphart) [reply src/compile/steps/write-to-note.ts:69]: I don't seem to be able to commit this change, but I'll remove them in the updated code.

File: src/compile/steps/write-to-note.ts (hunk 4 above)
Comment (b-camphart) [reply src/compile/steps/write-to-note.ts]: Modified into a recursive function :)

File: src/compile/steps/write-to-note.ts [hunk 9]
```diff
@@ -44,25 +44,119 @@ export const WriteToNoteStep = makeBuiltinStep({
...
+        // we moved up too many folders and ran out.
+        throw new Error("[Longform] Invalid path for Save as Note.")
+      }
+      // remove the lowest-level folder from the project path to move up, 
+      // and take this first component off the top of the filePathComponents
+      return resolveRelativeFilePath(projectPathComponents.slice(0, -1), filePathComponents.slice(1), false)
+    }
+    case ".": {
+      // relative to current folder
+      if (! atStartOfFilePath) {
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:146]:
```suggestion
      if (!atStartOfFilePath) {
```

File: src/compile/steps/write-to-note.ts [hunk 10]
```diff
@@ -44,25 +44,119 @@ export const WriteToNoteStep = makeBuiltinStep({
...
+        // illegal path like: ././filename.md
+        throw new Error("[Longform] Invalid path for Save as Note.")
+      }
+      // stay here, but remove the first filepath component
+      return resolveRelativeFilePath(projectPathComponents, filePathComponents.slice(1), false)
+    }
+    default: {
+      const filename = filePathComponents.last()
+      if (filename.startsWith(".")) {
+        new Notice("Obsidian cannot open files that begin with a dot. Consider a different name.");
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:156]: Thoughts on defaulting to something like `Compiled Manuscript.md` in this and saying such in the notice?

File: src/compile/steps/write-to-note.ts [hunk 11]
```diff
@@ -44,25 +44,119 @@ export const WriteToNoteStep = makeBuiltinStep({
...
+      }
+      // assume there are no more ".." in the rest of the filePathComponents
```
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:158]: Hmmm, this is a big assumption. One way around this is to use the third argument of this function as an accumulator (and treat the empty string as `atStartOfFilePath`), or we just loop through here and error if we see another `..`. Fine either way.

File: src/compile/steps/write-to-note.ts
Comment (kevboh) [inline src/compile/steps/write-to-note.ts:1]: Can you end this file with a newline? You can configure vscode to do this (and even save that config to this project, if you'd like).

**Review by kevboh — COMMENTED** [review]
Much more readable! A few nits.

File: src/compile/steps/write-to-note.ts (hunk 10 above)
Comment (b-camphart) [reply src/compile/steps/write-to-note.ts:156]: I just wonder how much responsibility the plugin should take on.  Having a file start with a dot isn't illegal, we can happily create, and write to, those files.  The issue comes from Obsidian not then being able to open it.  What if someone _intentionally_ started it with a dot?  Should we prevent them from creating the file they want, simply because Obsidian can't open it?  Plus, what if, later, Obsidian decides to support reading those files?  Or adds a setting to opt into reading them?  At least, with a warning like this, we're somewhat unified with Obsidian, but we won't prevent users from doing what they want (and we aren't blocking a potential future Obsidian feature).

File: src/compile/steps/write-to-note.ts (hunk 11 above)
Comment (b-camphart) [reply src/compile/steps/write-to-note.ts:158]: My reasoning around this was similar to the above: how much responsibility should we take on?  The comment isn't intended to say "we know there aren't any more `..` in the file path" but instead, "we're going to pretend like there aren't from here."  We could loop through the rest to see if there are more, then issue a warning about it, but I don't think we should prevent technically legal paths from being used.

File: src/compile/steps/write-to-note.ts (hunk 10 above)
Comment (kevboh) [reply src/compile/steps/write-to-note.ts:156]: Good points. Ignore me here.

File: src/compile/steps/write-to-note.ts (hunk 11 above)
Comment (kevboh) [reply src/compile/steps/write-to-note.ts:158]: My reading was that a path like `folder/../folder/../folder/file.md` would break. Is that not true?

Comment (b-camphart) [reply src/compile/steps/write-to-note.ts:158]: From my testing, my filesystem (Windows) happily created folders called ".." when I put a filepath like that in.  Now, that may not always be the case, based on the OS, but I figured, it would fail when we tried to create the file/folders anyway, if the OS didn't like it.

File: src/compile/steps/write-to-note.ts
Comment (b-camphart) [reply src/compile/steps/write-to-note.ts:1]: I _think_ I got my linter working in vscode now, so hopefully this won't be an issue again :)

File: src/compile/steps/write-to-note.ts (hunk 11 above)
Comment (kevboh) [reply src/compile/steps/write-to-note.ts:158]: Fair enough.

**Review by kevboh — APPROVED** [review]
